name: kurtlarvadisiimsakiye
description: Kurtlar Vadisi İmsakiyesi
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true