name: kurtlarvadisiimsakiye
description: Kurtlar Vadisi İmsakiyesi
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.2.0 #web-url hash
  url_launcher: ^6.0.9  #telefon link ve mail için iletişim paketi 
  shared_preferences: ^2.0.9 #local veri yönetimi
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true